import html, json
from datetime import datetime
from pathlib import Path
from core import VERSION, score, completion, recommendation


def export_report(rows,summary,path):
    s=score(rows); c=completion(rows); rec,note=recommendation(rows); gen=datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    rc={'BUY':'#168a5b','NEGOTIATE':'#b7791f','REJECT':'#c53030','INCOMPLETE':'#5b67d1'}[rec]
    trs=''.join(f"<tr><td>{html.escape(r['category'])}</td><td>{html.escape(r['item'])}</td><td>{html.escape(r['value'])}</td><td><b>{r['status']}</b></td><td>{html.escape(r['note'])}</td></tr>" for r in rows)
    model=' '.join(x for x in [summary.get('manufacturer',''),summary.get('model','')] if x) or 'Unknown laptop'
    bh=summary.get('battery_health'); btxt=f"{summary.get('battery_grade','—')} · {bh}%" if bh is not None else summary.get('battery_grade','—')
    doc=f'''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Laptop Check Pro Report</title><style>body{{font-family:Segoe UI,Arial;background:#edf3f9;color:#172033;margin:0;padding:24px}}main{{max-width:1180px;margin:auto}}header{{background:linear-gradient(135deg,#0f1b31,#1b3155);color:white;padding:28px;border-radius:18px}}.grid{{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin:16px 0}}.card{{background:#fff;padding:18px;border-radius:14px;box-shadow:0 8px 24px #1c2b4512}}.big{{font-size:32px;font-weight:800}}.rec{{background:{rc};color:#fff}}table{{width:100%;border-collapse:collapse;background:#fff}}th,td{{padding:10px;border-bottom:1px solid #e7edf5;text-align:left;vertical-align:top}}th{{background:#f6f9fc}}.note{{background:#fff;padding:18px;margin-top:16px;border-radius:14px}}@media(max-width:800px){{.grid{{grid-template-columns:1fr 1fr}}table{{display:block;overflow:auto}}}}</style></head><body><main><header><h1>Laptop Check Pro v{VERSION}</h1><h2>{html.escape(model)}</h2><p>{gen} · Service Tag: {html.escape(summary.get('serial') or 'Not reported')}</p></header><div class="grid"><div class="card"><div>Overall Health</div><div class="big">{s}/100</div></div><div class="card"><div>Test Completion</div><div class="big">{c}%</div></div><div class="card"><div>Battery</div><div class="big">{html.escape(str(btxt))}</div></div><div class="card rec"><div>Recommendation</div><div class="big">{rec}</div><div>{html.escape(note)}</div></div></div><table><tr><th>Category</th><th>Check</th><th>Result</th><th>Status</th><th>Note</th></tr>{trs}</table><div class="note"><b>Important:</b> Software cannot prove a used laptop is defect-free. Inspect body/hinge, ports, display, BIOS lock, charger, repair/liquid signs and real battery runtime. On Dell, run F12 ePSA diagnostics.</div></main></body></html>'''
    Path(path).write_text(doc,encoding='utf-8')
    Path(path).with_suffix('.json').write_text(json.dumps({'app':'Laptop Check Pro','version':VERSION,'generated':gen,'score':s,'completion':c,'recommendation':rec,'summary':summary,'results':rows},ensure_ascii=False,indent=2),encoding='utf-8')
